### ISSUE TITLE
[Bug]: Geometry differences between ifc-web demo site and components 3.1

### ISSUE THREAD

**Issue by robertbiskup** [ThatOpen/engine_web-ifc#1567]
### What happened?

Issue moved from "[Geometry differences between ifc-web demo site and components 3.1](https://github.com/ThatOpen/engine_components/issues/603#top)
#603". Files (ifc & frag) sent in a private message to @agviegas 
components:
<img width="992" height="844" alt="Image" src="https://github.com/user-attachments/assets/fb78e06c-bab0-44c3-aa30-0b6357837209" />
web-ifc demo:

<img width="2102" height="1398" alt="Image" src="https://github.com/user-attachments/assets/f19a2821-7d4a-47a6-9f50-7079df662722" />

### Version

"web-ifc":  "0.0.70"

### Relevant log output

```shell

```

**Comment by QuimMoya** [comment]
Setting PLANE_REFIT_ITERATIONS to 3 resolves the issue. You can configure this value in the loader settings.

**Comment by robertbiskup** [comment]
@QuimMoya I can't see this option in loader settings(components), there is only  COORDINATE_TO_ORIGIN, 

<img width="485" height="215" alt="Image" src="https://github.com/user-attachments/assets/efd73da0-cb00-4669-8d46-51235b02588c" />

<img width="436" height="596" alt="Image" src="https://github.com/user-attachments/assets/53eccf87-64e2-4eac-9fad-252480347d10" />

**Comment by agviegas** [comment]
@robertbiskup I need to publish a new version using the latest web-ifc. I'll do it these days!

**Comment by agviegas** [comment]
Hey @robertbiskup I think this is solved. Can you check [this](https://github.com/ThatOpen/engine_fragment/issues/92)? You should be able to tweak the parameters in the latest version of the ifcserializer. Thanks!

**Comment by robertbiskup** [comment]
@QuimMoya, @agviegas unfortunately the problem still exists: 

<img width="686" height="510" alt="Image" src="https://github.com/user-attachments/assets/c72c75fd-3284-4b79-b431-6cf9f1710043" />

<img width="781" height="406" alt="Image" src="https://github.com/user-attachments/assets/2ba28649-688c-47a9-916c-db9591fc7bae" />

<img width="639" height="745" alt="Image" src="https://github.com/user-attachments/assets/8f6d7530-69c9-480f-80bd-4589c50ff02d" />

I also tried with other parameter values (5,6,10), the effect was the same.. can you check this model in your "components"?

**Comment by agviegas** [comment]
@robertbiskup sorry I was not applying the ifcloader settings. I'll publish a patch now as `@thatopen/components@3.1.4`. I tried with `ifcLoader.settings.webIfc.PLANE_REFIT_ITERATIONS = 10;` and works:

<img width="810" height="734" alt="Image" src="https://github.com/user-attachments/assets/60a21374-d096-4dea-b4e2-2fe9c59c1046" />
