### ISSUE TITLE
[Bug]: Faulty ToRawLineData function for type "4186316022"

### ISSUE THREAD

**Issue by quasarchimaere** [ThatOpen/engine_web-ifc#1581]
### What happened?

Somehow if you want to use write Line for the type 4186316022 (ToRawLineData) the function in IFC2X3 is defined as follows: `  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingPropertyDefinition],`

But in IFC4 and IFC4X3 this line turns into `  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, Labelise(i.RelatingPropertyDefinition)],` which labelises the last param (reference to another ifc-line number) and thus causes an error when trying to call writeRawLineData with the RawLineData result

### Version

at least 0.0.69 and onwards (used to be just fine around 0.0.59)

### Relevant log output

```shell

```

**Comment by quasarchimaere** [comment]
Just as a note for anybody who wants this fixed too, i created a patch (with npm-patch-package) that resolves this issue:

https://www.npmjs.com/package/patch-package

```
diff --git a/node_modules/web-ifc/web-ifc-api-iife.js b/node_modules/web-ifc/web-ifc-api-iife.js
index 46d8d03..d1a6757 100644
--- a/node_modules/web-ifc/web-ifc-api-iife.js
+++ b/node_modules/web-ifc/web-ifc-api-iife.js
@@ -30936,7 +30936,7 @@ var WebIFC = (() => {
     2551354335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
     693640335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
     1462361463: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingObject],
-    4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, Labelise(i.RelatingPropertyDefinition)],
+    4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingPropertyDefinition],
     307848117: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedPropertySets, i.RelatingTemplate],
     781010003: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingType],
     3940055652: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatingOpeningElement, i.RelatedBuildingElement],
@@ -51793,7 +51793,7 @@ var WebIFC = (() => {
     2551354335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
     693640335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
     1462361463: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingObject],
-    4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, Labelise(i.RelatingPropertyDefinition)],
+    4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingPropertyDefinition],
     307848117: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedPropertySets, i.RelatingTemplate],
     781010003: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingType],
     3940055652: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatingOpeningElement, i.RelatedBuildingElement],
diff --git a/node_modules/web-ifc/web-ifc-api-node.js b/node_modules/web-ifc/web-ifc-api-node.js
index 4188533..e84d249 100644
--- a/node_modules/web-ifc/web-ifc-api-node.js
+++ b/node_modules/web-ifc/web-ifc-api-node.js
@@ -31008,7 +31008,7 @@ ToRawLineData[2] = {
   2551354335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   693640335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   1462361463: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingObject],
-  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, Labelise(i.RelatingPropertyDefinition)],
+  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingPropertyDefinition],
   307848117: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedPropertySets, i.RelatingTemplate],
   781010003: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingType],
   3940055652: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatingOpeningElement, i.RelatedBuildingElement],
@@ -51865,7 +51865,7 @@ ToRawLineData[3] = {
   2551354335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   693640335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   1462361463: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingObject],
-  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, Labelise(i.RelatingPropertyDefinition)],
+  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingPropertyDefinition],
   307848117: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedPropertySets, i.RelatingTemplate],
   781010003: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingType],
   3940055652: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatingOpeningElement, i.RelatedBuildingElement],
diff --git a/node_modules/web-ifc/web-ifc-api.js b/node_modules/web-ifc/web-ifc-api.js
index daeb407..7f7b010 100644
--- a/node_modules/web-ifc/web-ifc-api.js
+++ b/node_modules/web-ifc/web-ifc-api.js
@@ -29743,7 +29743,7 @@ ToRawLineData[2] = {
   2551354335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   693640335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   1462361463: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingObject],
-  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, Labelise(i.RelatingPropertyDefinition)],
+  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingPropertyDefinition],
   307848117: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedPropertySets, i.RelatingTemplate],
   781010003: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingType],
   3940055652: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatingOpeningElement, i.RelatedBuildingElement],
@@ -50600,7 +50600,7 @@ ToRawLineData[3] = {
   2551354335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   693640335: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description],
   1462361463: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingObject],
-  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, Labelise(i.RelatingPropertyDefinition)],
+  4186316022: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingPropertyDefinition],
   307848117: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedPropertySets, i.RelatingTemplate],
   781010003: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatedObjects, i.RelatingType],
   3940055652: (i) => [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.RelatingOpeningElement, i.RelatedBuildingElement],
```

**Comment by beachtom** [comment]
Are you able to share a file that can replicate this on?

**Comment by quasarchimaere** [comment]
i think that the file that i used had this content:

```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView_V2.0]'),'2;1');
FILE_NAME('test');
FILE_SCHEMA(('IFC4'));
ENDSEC;

DATA;
/** Geometry*/
#6= IFCCARTESIANPOINT((0.,0.,0.));
#31= IFCAXIS2PLACEMENT3D(#6,$,$);
#32= IFCLOCALPLACEMENT(#564,#31);
#93= IFCAXIS2PLACEMENT3D(#6,$,$);
#94= IFCDIRECTION((6.12303176911189E-17,1.));
#96= IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.00000000000000E-5,#93,#94);
#99= IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Axis','Model',*,*,*,*,#96,$,.GRAPH_VIEW.,$);
#101= IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Body','Model',*,*,*,*,#96,$,.MODEL_VIEW.,$);
#102= IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Box','Model',*,*,*,*,#96,$,.MODEL_VIEW.,$);
#103= IFCGEOMETRICREPRESENTATIONSUBCONTEXT('FootPrint','Model',*,*,*,*,#96,$,.MODEL_VIEW.,$);

/** Project -> Site -> Building */
#104= IFCPROJECT('1mr9nXm0P8fvao1q4hHXjc',$,'Projektnummer',$,$,'Projektname','Projektstatus',(#96),#91);
#565= IFCSITE('1mr9nXm0P8fvao1q4hHXja',$,'Default',$,'',#564,$,$,.ELEMENT.,(52,30,59,765625),(13,23,59,998626),0.,$,$);
#114= IFCBUILDING('1mr9nXm0P8fvao1q4hHXjd',$,'',$,$,#32,$,'',.ELEMENT.,$,$,$);
#653= IFCRELAGGREGATES('29v0dZW51BaevekU$xoGy3',$,$,$,#104,(#565));
#657= IFCRELAGGREGATES('1KqoWlBCf9tgSnzgHTaqtD',$,$,$,#565,(#114));

/** Units*/
#42= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#49= IFCSIUNIT(*,.MASSUNIT.,.KILO.,.GRAM.);
#50= IFCDERIVEDUNITELEMENT(#49,1);
#51= IFCDERIVEDUNITELEMENT(#42,-3);
#52= IFCDERIVEDUNIT((#50,#51),.MASSDENSITYUNIT.,$);
#91= IFCUNITASSIGNMENT((#42,#49,#52));

/** Wall*/
#120= IFCCARTESIANPOINT((0.,0.,-3.));
#122= IFCAXIS2PLACEMENT3D(#120,$,$);
#127= IFCAXIS2PLACEMENT3D(#6,$,$);
#128= IFCLOCALPLACEMENT(#32,#127);
#647= IFCRELCONTAINEDINSPATIALSTRUCTURE('13LV5dTeP3CAox54$56C1Z',$,$,$,(#345),#104);
#161= IFCCOLOURRGB($,0.968627450980392,0.968627450980392,0.968627450980392);
#162= IFCSURFACESTYLERENDERING(#161,0.,$,$,$,$,IFCNORMALISEDRATIOMEASURE(0.5),IFCSPECULAREXPONENT(128.),.NOTDEFINED.);
#163= IFCSURFACESTYLE('Stahlbeton - Ortbeton',.BOTH.,(#162));
#165= IFCPRESENTATIONSTYLEASSIGNMENT((#163));
#222= IFCPROPERTYSINGLEVALUE('Phase erstellt',$,IFCLABEL('Phase 1'),$);
#283= IFCPROPERTYSET('0m0f03tmn2$uLR5br3Hdyv',$,'Phasen',$,(#222));
#285= IFCRELDEFINESBYPROPERTIES('0m0f03tmn2$uLR5rr3Hdyv',$,$,$,(#345),#283);
#322= IFCCARTESIANPOINT((-1.75,0.,0.));
#324= IFCAXIS2PLACEMENT3D(#322,$,$);
#325= IFCLOCALPLACEMENT(#128,#324);
#326= IFCCARTESIANPOINT((3.5,0.));
#9= IFCCARTESIANPOINT((0.,0.));
#328= IFCPOLYLINE((#9,#326));
#332= IFCCARTESIANPOINT((1.75,-7.63278329429795E-17));
#25= IFCDIRECTION((-1.,0.));
#334= IFCAXIS2PLACEMENT2D(#332,#25);
#335= IFCRECTANGLEPROFILEDEF(.AREA.,$,#334,3.5,0.249999999999999);
#336= IFCAXIS2PLACEMENT3D(#6,$,$);
#19= IFCDIRECTION((0.,0.,1.));
#337= IFCEXTRUDEDAREASOLID(#335,#336,#19,4.);
#338= IFCSTYLEDITEM(#337,(#165),$);
#330= IFCSHAPEREPRESENTATION(#99,'Axis','Curve2D',(#328));
#341= IFCSHAPEREPRESENTATION(#101,'Body','SweptSolid',(#337));
#343= IFCPRODUCTDEFINITIONSHAPE($,$,(#330,#341));
#345= IFCWALLSTANDARDCASE('0CUddw_UD3HAXeW9DuznTO',$,'Basiswand:CAx_200+_AW_NITR_BN_0,25:435656',$,'Basiswand:CAx_200+_AW_NITR_BN_0,25:376017',#325,#343,'435656');
#563= IFCAXIS2PLACEMENT3D(#6,$,$);
#564= IFCLOCALPLACEMENT($,#563);
ENDSEC;

END-ISO-10303-21;

```
Line `#285` should be the IfcRelDefinesByProperties that causes the issue when writing rawLines

**Comment by beachtom** [comment]
Apologies - I believe this has been fixed I just forgot to close the issue - please re-open if this is not the case

**Comment by quasarchimaere** [comment]
@beachtom i just checked this with web-ifc 0.0.77 and the error still exists -> as seen in the generated web-ifc-api code for key 4186316022 -> the Labelise is still present as a wrapper around the parameter and thus a patch is still needed
