### ISSUE TITLE
Quality problem in CIVIL models

### ISSUE THREAD

**Issue by LukasKStavario** [ThatOpen/engine_web-ifc#1622]
### Describe the bug 📝

We have a CIVIL models that are displaying in poor quality

<img width="1166" height="918" alt="Image" src="https://github.com/user-attachments/assets/38e2d598-305e-4d2d-8501-df0ba9f92e40" />

<img width="1479" height="1336" alt="Image" src="https://github.com/user-attachments/assets/fc18dea8-a23f-4ff4-b0f8-2cbcc4cced74" />

Using newest version and setting quality to maximum.

                fragments.list.onItemSet.add(({ value: model }) => {
                    model.graphicsQuality = 1;
                    model.useCamera(worldState.camera.three);
                    worldState.scene.three.add(model.object);
                    fragments.core.update(true);
                    delay(500).then(() => {
                        worldState.camera.fitToItems();
                    });
                });

### System Info 💻

```shell
3.1.7
```

### Used Package Manager 📦

npm

### Validations ✅

- [x] Read the [docs](https://docs.thatopen.com/intro).
- [x] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [x] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
@LukasKStavario can you please send us the files to antonio@thatopen.com to check them?

**Comment by agviegas** [comment]
Model privately shared [here](https://drive.google.com/drive/folders/1ZNcVaOHjxEVmaVxGx_QXCQ6WNp0gReI0).

**Comment by LukasKStavario** [comment]
We have another model with even worse problems. Any news on this?

<img width="2633" height="1002" alt="Image" src="https://github.com/user-attachments/assets/857e35d9-12e0-417e-9b91-650a314ab810" />

**Comment by agviegas** [comment]
Also happening in web-ifc. Moving the issue there

<img width="1074" height="560" alt="Image" src="https://github.com/user-attachments/assets/50187d25-99a0-4217-ac6e-187548d7ed7f" />

**Comment by beachtom** [comment]
I think this is now fixed!

**Comment by LukasKStavario** [comment]
<img width="1931" height="1301" alt="Image" src="https://github.com/user-attachments/assets/1409bdd6-5997-4c16-bbe9-55bfbfade9a2" />

Unfortunately, I still see holes in the slopes

**Comment by agviegas** [comment]
@LukasKStavario did you update web-ifc to the latest version (including the reference to the WASM file)? If so, do you perceive any changes with the previous version or is it exactly the same?

**Comment by LukasKStavario** [comment]
yes, I have change it in my translation node js server to 0.0.72 and even in displaying react app to the same version, change the node wasm file in translation server, delete all caches, translate model again, download new browser but still the same, could the problem be in fragments? But from previous 0.0.71 I can see lot of changes in graphics.

**Comment by agviegas** [comment]
@LukasKStavario I see. We have a big release in 3 days so won't have time until then. But after that, we'll take care promptly. Thanks for your patience!
