### ISSUE TITLE
[Bug]: IFC[X]STYLE Lines are parsed incorrectly

### ISSUE THREAD

**Issue by quasarchimaere** [ThatOpen/engine_web-ifc#498]
### What happened?

Reading a given file that includes Style Lines (e.g. IFCWINDOWSTYLE, IFCDOORSTYLE etc.) and writing the file again alters the structure of the line
input:
`#14689=IFCWINDOWSTYLE('2C0fafuFn0nQji3L0rllPh',#41,'xyz',$,$,(#14688,#14744,#14747),(#14687),'4600958',.NOTDEFINED.,.NOTDEFINED.,.F.,.F.);`
output:
`#14689=IFCWINDOWSTYLE('2C0fafuFn0nQji3L0rllPh',#41,'xyz',$,$,(#14688,#14744,#14747),(#14687),'4600958',.NOTDEFINED.,.NOTDEFINED.,'F','F');`

as you can see it seems like the arguments are parsed incorrectly for the last two parameters: afaik the type is set to 2 (which turns into a string) instead of being an enum (as bool values are supposed to be)

### Version

0.0.44

### Anything else?
The Parameters of the respective classes are:
`ParameterTakesPrecedence: boolean`
`Sizeable: boolean`

The reason why this happens is also seen "clearly" within the ToRawLine function map:
`1299126871: (i) => {
    var _a, _b;
    return [i.GlobalId, i.OwnerHistory, i.Name, i.Description, i.ApplicableOccurrence, i.HasPropertySets, i.RepresentationMaps, i.Tag, i.ConstructionType, i.OperationType, (_a = i.ParameterTakesPrecedence) == null ? void 0 : _a.toString(), (_b = i.Sizeable) == null ? void 0 : _b.toString()];
  },`
look at `i.ParameterTakesPrecedence` if this isnt null it will use a .toString() instead of Labelising it to the appropriate type

**Comment by beachtom** [comment]
This should now be fixed

**Comment by quasarchimaere** [comment]
i just checked this with the new 0.0.46 version, and the issue still exists @beachtom 
WANTED -->  `#8923=IFCWINDOWSTYLE([XXXXXXXXXXXXX],.NOTDEFINED.,.NOTDEFINED.,.F.,.F.);`
ACTUAL --> `#8923=IFCWINDOWSTYLE([XXXXXXXXXXXXX],.NOTDEFINED.,.NOTDEFINED.,'F','F');`

**Comment by beachtom** [comment]
OK think is this really fixed now!

**Comment by quasarchimaere** [comment]
saw in web-ifc@p0.0.51 that this issue still persists, was there a regression? idk, i haven't seen it actually parse `.T.` `.F.` or `.U.` in any of the versions

**Comment by quasarchimaere** [comment]
> saw in web-ifc@p0.0.51 that this issue still persists, was there a regression? idk, i haven't seen it actually parse `.T.` `.F.` or `.U.` in any of the versions

@beachtom

**Comment by quasarchimaere** [comment]
@beachtom just checked with 0.0.52 and the issue is still present

**Comment by beachtom** [comment]
So I can get it generate lines like:

#14313=IFCWINDOWSTYLE(14313.,'2C0fafuFn0nQji3L0rllPh',$,'xyz',$,$,$,$,$,$,.F.,.T.);

Can you share the code you are using to manipulate the line and I can help debug from there

**Comment by quasarchimaere** [comment]
i do not manipulate the style rows at all, it happens "automatically" when writing the model to a new file again (the changes that have been made are regarding other lines)

**Comment by beachtom** [comment]
OK thanks that's useful

**Comment by quasarchimaere** [comment]
i think i have to dive deeper into what is going on within my solution, as of now it does not seem to do the appropriate write in either of the versions 0.0.54 and 0.0.53 i will hopefully find out whats wrong, or at least provide some more insight (or a ifc file) to reproduce this. many thanks for looking into it

**Comment by quasarchimaere** [comment]
@beachtom ok, i just think i found out whats happening, because i just got it to work with an ifc4 file, but the tests but not with an ifc2x3. Looking at the web-ifc code the generated FromRawDataLines for example "WindowStyle" look like this:

### IFC4
```
1299126871: (v) => new IFC4.IfcWindowStyle(new IFC4.IfcGloballyUniqueId(!v[0] && v[0] != "" ? null : v[0].value), !v[1] && v[1] != "" ? null : new Handle(!v[1] && v[1] != "" ? null : v[1].value), !v[2] && v[2] != "" ? null : new IFC4.IfcLabel(!v[2] && v[2] != "" ? null : v[2].value), !v[3] && v[3] != "" ? null : new IFC4.IfcText(!v[3] && v[3] != "" ? null : v[3].value), !v[4] && v[4] != "" ? null : new IFC4.IfcIdentifier(!v[4] && v[4] != "" ? null : v[4].value), !v[5] && v[5] != "" ? null : v[5]?.map((p) => p?.value && p?.value != "" ? new Handle(p.value) : null) || [], !v[6] && v[6] != "" ? null : v[6]?.map((p) => p?.value && p?.value != "" ? new Handle(p.value) : null) || [], !v[7] && v[7] != "" ? null : new IFC4.IfcLabel(!v[7] && v[7] != "" ? null : v[7].value), v[8], v[9], new IFC4.IfcBoolean(!v[10] && v[10] != "" ? null : v[10].value), new IFC4.IfcBoolean(!v[11] && v[11] != "" ? null : v[11].value)),
```
###IFC2X3
```
1299126871: (v) => new IFC2X3.IfcWindowStyle(new IFC2X3.IfcGloballyUniqueId(!v[0] && v[0] != "" ? null : v[0].value), new Handle(!v[1] && v[1] != "" ? null : v[1].value), !v[2] && v[2] != "" ? null : new IFC2X3.IfcLabel(!v[2] && v[2] != "" ? null : v[2].value), !v[3] && v[3] != "" ? null : new IFC2X3.IfcText(!v[3] && v[3] != "" ? null : v[3].value), !v[4] && v[4] != "" ? null : new IFC2X3.IfcLabel(!v[4] && v[4] != "" ? null : v[4].value), !v[5] && v[5] != "" ? null : v[5]?.map((p) => p?.value && p?.value != "" ? new Handle(p.value) : null) || [], !v[6] && v[6] != "" ? null : v[6]?.map((p) => p?.value && p?.value != "" ? new Handle(p.value) : null) || [], !v[7] && v[7] != "" ? null : new IFC2X3.IfcLabel(!v[7] && v[7] != "" ? null : v[7].value), v[8], v[9], !v[10] && v[10] != "" ? null : v[10].value, !v[11] && v[11] != "" ? null : v[11].value),
```

Looking at parameter v[10] and v[11] within both of the implementations you can see that in case of IFC4 the param is properly created as a boolean value, where as the ifc2x3 file does not.

I am not sure that this is the actual problem (as i don't know if unchanged lines are kept in the wasm/cpp part of web-ifc, but maybe there is a difference there as well.

How to reproduce:
Copy one of the proper lines above into any ifc2x3 file that you have, and write the model to a new file without making any changes. then you should see that the line you added does not properly parse the last two bool params
