### ISSUE TITLE
[Bug]: single quote in strings such as property name does not survive write-read-write roundtrip

### ISSUE THREAD

**Issue by fkleedorfer** [ThatOpen/engine_web-ifc#636]
### What happened?

We have a property name, `Winkel_'`. Writing that property to an ifc file yields:

`#336=IFCPROPERTYSINGLEVALUE('Winkel_\X2\00B0\X0\',$,IFCPLANEANGLEMEASURE(130.),#273);`

when we read that file with ifc.js, modify the value and write it again, this is the output:

`#573=IFCPROPERTYSINGLEVALUE('Winkel_'',$,IFCPLANEANGLEMEASURE(7799.999982123717),#462);`      

Note the double single quote at the end of the property name: `''`

### Version

0.0.46

EDIT: re-examined where the problem occurs and updated the description

**Comment by beachtom** [comment]
This is fixed

**Comment by quasarchimaere** [comment]
@beachtom this is not fixed, (versions 0.0.52 and 0.0.51 alike)

output of 0.0.51
`#393=IFCPROPERTYSINGLEVALUE('Winkel_'',$,IFCPLANEANGLEMEASURE(7799.999982123717),#392);`

output of 0.0.52
`#393=IFCPROPERTYSINGLEVALUE('Winkel_''',$,IFCPLANEANGLEMEASURE(7799.999982123717),#392);`

expected:
`#393=IFCPROPERTYSINGLEVALUE('Winkel_\X2\00B0\X0\',$,IFCPLANEANGLEMEASURE(7799.999982123717),#392);`

**Comment by beachtom** [comment]
So '' is actually correct. From me reading the IFC spec there are multiple ways to encode a quote in the text and one of the is to encode it with an extra quote - so the file should still be valid - I check they open with Solibri and work.

So a correct representation of '' is '''  the other representation is correct as well
